name: 'Run "bake"'
description: 'Executes the convention based build command "bake"'

inputs:
  # REQUIRED ==============================================================
  version:
    description: 'Version of bake to use. ALWAYS use a specific version!'
    required: true
  args:
    description: 'Arguments passed diredctly yo bake'
    required: true
  # OPTIONAL ==============================================================
  version:
    dotnet-version: '.NET version to install. Should match the version used by bake'
    required: false
    default: '8.0.x'

runs:
  using: "composite"
  steps:
  - name: Install .NET dependency
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '${{ inputs.dotnet-version }}'

  - name: Run bake
    shell: bash
    run: |
      dotnet tool install --global Bake --version ${{ inputs.bake-version }}
      export PATH="$PATH:/home/ubuntu/.dotnet/tools"
      
      bake ${{ inputs.args }}
