name: pull-requests

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.
      with:
        version: '0.30.43-beta'
        args: '--version'
